# Generated by Django 2.2.8 on 2019-12-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='descripcion de la categoria', max_length=100, unique=True),
        ),
    ]
